# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/aptay/Downloads/Nexys-Video-HDMI-master/Nexys-Video-HDMI-master/src/bd/hdmi/ip/hdmi_v_tc_1_0/hdmi_v_tc_1_0.xci
# IP: The module: 'hdmi_v_tc_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/aptay/Downloads/Nexys-Video-HDMI-master/Nexys-Video-HDMI-master/src/bd/hdmi/ip/hdmi_v_tc_1_0/hdmi_v_tc_1_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_v_tc_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/aptay/Downloads/Nexys-Video-HDMI-master/Nexys-Video-HDMI-master/src/bd/hdmi/ip/hdmi_v_tc_1_0/hdmi_v_tc_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_v_tc_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/aptay/Downloads/Nexys-Video-HDMI-master/Nexys-Video-HDMI-master/src/bd/hdmi/ip/hdmi_v_tc_1_0/hdmi_v_tc_1_0.xci
# IP: The module: 'hdmi_v_tc_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/aptay/Downloads/Nexys-Video-HDMI-master/Nexys-Video-HDMI-master/src/bd/hdmi/ip/hdmi_v_tc_1_0/hdmi_v_tc_1_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_v_tc_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/aptay/Downloads/Nexys-Video-HDMI-master/Nexys-Video-HDMI-master/src/bd/hdmi/ip/hdmi_v_tc_1_0/hdmi_v_tc_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_v_tc_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
